### ISSUE TITLE
Accuracy issues

### ISSUE THREAD

**Issue by iasiimwe** [Selbosh/doseminer#2]
Thanks for this package. I need to extract doses and units from free text, so I tried this. However, there are some accuracy issues you should probably look into. For example, if you run the code:
`extract_from_prescription(c("Diclofenac sodium 50mg gastro-resistant tablets",
       "Bendroflumethiazide 2.5mg tablets",
       "Co-amoxiclav 250mg/125mg tablets",
       "Zyban 150mg modified-release tablets (GlaxoSmithKline UK Ltd)"))`, you get the wrong units (first two examples), fail to detect the clavulanate dose (third example) and extract a non-existent frequency (last example).

![image](https://user-images.githubusercontent.com/105666354/235720124-b6482754-917b-45b5-9546-836d121cbf2c.png)

**Comment by Selbosh** [comment]
Thanks for highlighting this! I will see if I can tweak the rules to capture these cases.

What would you'd expect the `dose` to be in the 3rd example? A range from 125-250mg or something else?

The last one is particularly interesting; I suspect it is misinterpreting `td` as the Latin 'ter die', but I will do some debugging to check.

Thanks again for pointing these issues out.
